DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    FIO VARCHAR(255),
    BIRTHDAY DATE,
    DATE_OF_DEATH DATE
);

DROP TABLE IF EXISTS AUTHORS_LITERARY_PRODUCTIONS;
CREATE TABLE AUTHORS_LITERARY_PRODUCTIONS(
     ID BIGINT NOT NULL,
     NAME VARCHAR(255) NOT NULL,
     AUTHOR_ID BIGINT NOT NULL);
CREATE SEQUENCE LITERARY_PRODUCTIONS_SEQ;

DROP TABLE IF EXISTS GENRES;
 CREATE TABLE GENRES(
     ID BIGSERIAL NOT NULL PRIMARY KEY,
     NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
     ID BIGINT,
     NAME VARCHAR(255),
     ISBN VARCHAR(255),
     LITERARY_ID BIGINT,
     GENRE_ID BIGINT);
CREATE SEQUENCE BOOKS_SEQ START WITH 100;