DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    FIO VARCHAR(255),
    BIRTHDAY DATE,
    DATE_OF_DEATH DATE
);

DROP TABLE IF EXISTS LITERARY;
CREATE TABLE LITERARY(
     ID BIGINT NOT NULL PRIMARY KEY,
     NAME VARCHAR(255) NOT NULL);
CREATE SEQUENCE LITERARY_SEQ;

DROP TABLE IF EXISTS AUTHORS_IN_LITERARY;
CREATE TABLE AUTHORS_IN_LITERARY(
      AUTHOR_ID BIGINT,
      LITERARY_ID BIGINT,
      foreign key (AUTHOR_ID) references AUTHORS,
      foreign key (LITERARY_ID) references LITERARY);

DROP TABLE IF EXISTS GENRES;
 CREATE TABLE GENRES(
     ID BIGSERIAL NOT NULL PRIMARY KEY,
     NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
     ID BIGSERIAL NOT NULL PRIMARY KEY,
     NAME VARCHAR(255),
     ISBN VARCHAR(255),
     GENRE_ID BIGINT);
CREATE SEQUENCE BOOKS_SEQ;

DROP TABLE IF EXISTS LITERARY_IN_BOOKS;
CREATE TABLE LITERARY_IN_BOOKS(
      BOOK_ID BIGINT,
      LITERARY_ID BIGINT,
      foreign key (BOOK_ID) references BOOKS,
      foreign key (LITERARY_ID) references LITERARY);


